### ISSUE TITLE
French localisation

### ISSUE THREAD

**Issue by jtesse** [h5p/h5p-image#2]
Hello,
part of the French translation is not considered. These are the license information.
Best regards

**Comment by icc** [comment]
Hi! These are deprecated and will be removed soon. The H5P plugin now has built-in support for copyrights on all media. The fields in question were only used before the plugin received this support.

I.e. there is really no need to translate this. But thank you for keeping an eye open and pointing it out :-)

**Comment by jtesse** [comment]
Thank you,
Where are the files for the translation of these fields?

**Comment by icc** [comment]
Actually they have to be translated as part of the plugin or module, so if you're using WordPress it's in the .po files in the language folder of the plugin, or if you're using Drupal I believe it can be done via [Drupal's Localize Service](https://localize.drupal.org/).

However, I see now that these are actually missing the translate function, so they can't be translated yet. 
I will add the function so that they can be translated from the next version on. Apologies for the inconvenience!

The strings can be found in [h5p.classes.php:3376](https://github.com/h5p/h5p-php-library/blob/master/h5p.classes.php#L3376) as part of the _getCopyrightSemantics()_ function.
