### ISSUE TITLE
No way to edit alt tag

### ISSUE THREAD

**Issue by tjb328** [h5p/h5p-image#4]
There is currently no way to edit the alt text of an image. I am using h5p in Drupal and can't seem to find an edit for the alt text in multiple interactive content types:

Dialog Cards
Collage(this also doesn't seem to use the h5p-image item correctly at all)
Flash Cards
Greeting Card
Guess the answer
Image Hotspots
Memory Game
Question Set
Timeline

Alt Tag editing available in:
Documentation tool
Fill in the blanks

**Comment by thomasmars** [comment]
This is because they are not using the H5P.Image library, they are using the "image" type from the native H5P semantics: https://h5p.org/semantics#guides-header-8

Some of them should definitely be changed, but the changes must be done in the respective repositories. Would be wonderful if you could create issues for this in their repositories and close this issue.

**Comment by tjb328** [comment]
I closed this issue and opened a new one up for each of the projects I mentioned.

Thanks
